---
__tmp_dir:              "{{ tmp_dir | default('/opt/IBM/Binaries') }}"
__was_tmp_dir:          "{{ __tmp_dir }}/was"
__sdk_tmp_dir:          "{{ __tmp_dir }}/sdk"
__logs_dir:             "{{ tmp_dir | default('/opt/IBM/Binaries') }}/logs"
__iim_install_location: "{{ iim_install_location  | default('/opt/IBM/InstallationManager') }}"
__was_install_location: "{{ was_install_location  | default('/opt/IBM/WebSphere/AppServer') }}"
__imshared_location:    "{{ imshared_location  | default('/opt/IBM/IMShared') }}"
__now:                  "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
__rsp_file:             "{{ __logs_dir }}/was_nd.rsp"
__log_file:             "{{ __logs_dir }}/was_nd_install.{{ __now }}.log"
__tpl_file:             "was_nd.rsp.j2"
__was_files:
  - { file_name: WAS_ND_V9.0_MP_ML.zip, check_sum: 3a9784b7dd2975c27c77a25db838a8e03c3e3b0f5cc06ba35cc620dd220424bd }
__sdk_files:
  - { file_name: ibm-java-sdk-8.0-7.5-linux-x64-installmgr.zip, check_sum: 79c7110ceda50468ed7dd85915ca062249ebb837a0e56cf9693510461dbd5dfa }

__was_version:          "{{ was_version | default('9.0.0.20160526_1854') }}"
__sdk_version:         "{{ java_versioin | default('8.0.7005.20220209_1019') }}"
__product_id:           "\"id='com.ibm.websphere.ND.v90'\""
__version_check:        "Installed com.ibm.websphere.ND.v90_9.0.0"
__iim_product_id:       "\"id='com.ibm.cic.agent\""
