---
- name:          "Is AdminCtl Running?"
  shell:         ps -p `cat "{{ __ihs_install_location }}/logs/admin.pid"`
  register:      adminctl_is_running
  ignore_errors: true

- name:          "Start AdminCtl"
  command:       "{{ __ihs_install_location }}/bin/adminctl start"
  register:      adminctl_start
  changed_when:  adminctl_start.rc == 0
  failed_when:   adminctl_start.rc != 0
  when:          adminctl_is_running.rc != 0

- name:          "Is AdminCtl Running?"
  shell:         ps -p `cat "{{ __ihs_install_location }}/logs/admin.pid"`
  register:      adminctl_is_running
  ignore_errors: true
  when:          (adminctl_start.rc is defined) and (adminctl_start.rc == 0)

- name:          Wait 10 seconds for AdminCtl to activate
  pause:
    seconds:     10
  when:          (adminctl_start.rc is defined) and (adminctl_start.rc == 0)
