---
__tmp_dir:              "{{ tmp_dir | default('/opt/IBM/Binaries') }}"
__was_fix_tmp_dir:      "{{ __tmp_dir }}/was_fixes"
__logs_dir:             "{{ __tmp_dir }}/logs"
__iim_install_location: "{{ iim_install_location  | default('/opt/IBM/InstallationManager') }}"
__was_install_location: "{{ was_install_location  | default('/opt/IBM/WebSphere/AppServer') }}"
__imshared_location:    "{{ imshared_location  | default('/opt/IBM/IMShared') }}"
__now:                  "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
__rsp_file:             "{{ __logs_dir }}/was_nd_fixes.rsp"
__log_file:             "{{ __logs_dir }}/was_nd_fixes_install.{{ __now }}.log"
__tpl_file:             "was_nd_fixes.rsp.j2"

__was_version:          "{{ was_version | default('v90') }}"

__this_version:         "{{ was_fp_version | default( __was_fp_version_latest ) }}"
__was_fix_files:        "{{ was_fp_files | default( __was_fp_files_latest ) }}"
__version_check:        "Updated to com.ibm.websphere.ND.v90_{{ __this_version }}"
__product_id:           "\"id='com.ibm.websphere.ND.v90' version='{{ __this_version }}'\""

__iim_product_id:       "\"id='com.ibm.cic.agent\""
__was_product_id:       "\"id='com.ibm.websphere.ND.v90'\""
#__was_product_id:       "\"id='com.ibm.websphere.ND.'\"{{ __was_version }}"


__was_fp_version_latest:  "9.0.5010.20211108_1200"
__was_fp_files_latest:
  - { file_name: 9.0.5-WS-WAS-FP010.zip, check_sum: f67612fc02dd14e991cc0dc4790e4ad6de5e96398b34d74193b2c75876cca0b9 }


## Old Versions
__was_fp_version_90510:  "9.0.5010.20211108_1200"
__was_fp_files_90510:
  - { file_name: 9.0.5-WS-WAS-FP010.zip, check_sum: f67612fc02dd14e991cc0dc4790e4ad6de5e96398b34d74193b2c75876cca0b9 }
