---
- name:          Cleanup Binaries directory
  file:          path={{ __tmp_dir }} state=absent
  ignore_errors: true

- name:          Create IHS Binaries directory
  file:          path={{ __ihs_tmp_dir }} state=directory mode=0755

- name:          Create PLG Binaries directory
  file:          path={{ __plg_tmp_dir }} state=directory mode=0755

- name:          Create WCT Binaries directory
  file:          path={{ __wct_tmp_dir }} state=directory mode=0755

- name:          Create SDK Binaries directory
  file:          path={{ __sdk_tmp_dir }} state=directory mode=0755

- name:          Create Logs directory
  file:          path={{ __logs_dir }} state=directory mode=0755

- name:          Download IBM HTTP Server Files
  get_url:
    url:         "{{ __ihs_repository_url }}/{{ item.file_name }}"
    dest:        "{{ __ihs_tmp_dir }}/{{ item.file_name }}"
    mode:        0755
    checksum:    sha256:{{ item.check_sum }}
  with_items:    "{{ __ihs_files }}"

- name:          Download WebSphere Plugins Files
  get_url:
    url:         "{{ __plg_repository_url }}/{{ item.file_name }}"
    dest:        "{{ __plg_tmp_dir }}/{{ item.file_name }}"
    mode:        0755
    checksum:    sha256:{{ item.check_sum }}
  with_items:    "{{ __plg_files }}"

- name:          Download WCT Files
  get_url:
    url:         "{{ __wct_repository_url }}/{{ item.file_name }}"
    dest:        "{{ __wct_tmp_dir }}/{{ item.file_name }}"
    mode:        0755
    checksum:    sha256:{{ item.check_sum }}
  with_items:    "{{ __wct_files }}"

- name:          Download SDK Files
  get_url:
    url:         "{{ __sdk_repository_url }}/{{ item.file_name }}"
    dest:        "{{ __sdk_tmp_dir }}/{{ item.file_name }}"
    mode:        0755
    checksum:    sha256:{{ item.check_sum }}
  with_items:    "{{ __sdk_files }}"

- name:          Extract IBM HTTP Server Files
  unarchive:
    src:         "{{ __ihs_tmp_dir }}/{{ item.file_name }}"
    dest:        "{{ __ihs_tmp_dir }}/"
    copy:        no
  with_items:    "{{ __ihs_files }}"

- name:          Extract WebSphere Plugins Files
  unarchive:
    src:         "{{ __plg_tmp_dir }}/{{ item.file_name }}"
    dest:        "{{ __plg_tmp_dir }}/"
    copy:        no
  with_items:    "{{ __plg_files }}"

- name:          Extract WCT Files
  unarchive:
    src:         "{{ __wct_tmp_dir }}/{{ item.file_name }}"
    dest:        "{{ __wct_tmp_dir }}/"
    copy:        no
  with_items:    "{{ __wct_files }}"

- name:          Extract SDK Files
  unarchive:
    src:         "{{ __sdk_tmp_dir }}/{{ item.file_name }}"
    dest:        "{{ __sdk_tmp_dir }}/"
    copy:        no
  with_items:    "{{ __sdk_files }}"

- name:          Generate Response file
  template:
    src:         "{{ __tpl_file }}"
    dest:        "{{ __rsp_file }}"

- name:          Install IBM HTTP Server / Plugin / WCT Software
  command:
    chdir={{ __tmp_dir }}
    {{ __iim_install_location }}/eclipse/tools/imcl -acceptLicense -sVP -log {{ __log_file }} input {{ __rsp_file }}
  register:      cout
  changed_when:  ( cout.stdout.find(__version_check) != -1)

- name:          Cleanup Binaries directory
  file:
    state:       absent
    path:        "{{ __tmp_dir }}"
