---
- name:          Create Binaries directory
  file:          path={{ __tmp_dir }} state=directory mode=0755

- name:          Create WAS Binaries directory
  file:          path={{ __was_tmp_dir }} state=directory mode=0755

- name:          Create SDK Binaries directory
  file:          path={{ __sdk_tmp_dir }} state=directory mode=0755

- name:          Create Logs directory
  file:          path={{ __logs_dir }} state=directory mode=0755

- name:          Download WAS ND V9.0 Files
  get_url:
    url:         "{{ was_repository_url }}/{{ item.file_name }}"
    dest:        "{{ __was_tmp_dir }}/{{ item.file_name }}"
    mode:        0755
    checksum:    sha256:{{ item.check_sum }}
  with_items:    "{{ __was_files }}"

- name:          Download SDK v8.0 Files
  get_url:
    url:         "{{ sdk_repository_url }}/{{ item.file_name }}"
    dest:        "{{ __sdk_tmp_dir }}/{{ item.file_name }}"
    mode:        0755
    checksum:    sha256:{{ item.check_sum }}
  with_items:    "{{ __sdk_files }}"

- name:          Extract WAS ND V9.0 Files
  unarchive:
    src:         "{{ __was_tmp_dir }}/{{ item.file_name }}"
    dest:        "{{ __was_tmp_dir }}/"
    copy:        no
  with_items:    "{{ __was_files }}"

- name:          Extract SDK V8.0 Files
  unarchive:
    src:         "{{ __sdk_tmp_dir }}/{{ item.file_name }}"
    dest:        "{{ __sdk_tmp_dir }}/"
    copy:        no
  with_items:    "{{ __sdk_files }}"

- name:          Generate WAS Response file
  template:
    src:         "{{ __tpl_file }}"
    dest:        "{{ __rsp_file }}"

- name:          Install IBM WebSphere Application Server
  command:
    chdir={{ __tmp_dir }}
    {{ __iim_install_location }}/eclipse/tools/imcl -acceptLicense -sVP -log {{ __log_file }} input {{ __rsp_file }}
  register:      cout
  changed_when:  ( cout.stdout.find( __version_check ) != -1)

- name:          Cleanup WAS Binaries directory
  file:          path={{ __was_tmp_dir }} state=absent

- name:          Cleanup SDK Binaries directory
  file:          path={{ __sdk_tmp_dir }} state=absent
