---
__ihs_repository_url:   "{{ ihs_repository_url }}"
__plg_repository_url:   "{{ plg_repository_url }}"
__wct_repository_url:   "{{ wct_repository_url }}"
__sdk_repository_url:   "{{ sdk_repository_url }}"
__tmp_dir:              "{{ tmp_dir | default('/opt/IBM/Binaries') }}"
__ihs_tmp_dir:          "{{ __tmp_dir }}/ihs"
__plg_tmp_dir:          "{{ __tmp_dir }}/plg"
__wct_tmp_dir:          "{{ __tmp_dir }}/wct"
__sdk_tmp_dir:          "{{ __tmp_dir }}/sdk"
__logs_dir:             "{{ __tmp_dir }}/logs"
__iim_install_location: "{{ iim_install_location  | default('/opt/IBM/InstallationManager') }}"
__ihs_install_location: "{{ ihs_install_location  | default('/opt/IBM/HTTPServer') }}"
__plg_install_location: "{{ plg_install_location  | default('/opt/IBM/WebSphere/Plugins') }}"
__wct_install_location: "{{ wct_install_location  | default('/opt/IBM/WebSphere/Toolbox') }}"
__imshared_location:    "{{ imshared_location  | default('/opt/IBM/IMShared') }}"
__now:                  "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
__rsp_file:             "{{ __logs_dir }}/ihs_plg_wct.rsp"
__log_file:             "{{ __logs_dir }}/ihs_install.{{ __now }}.log"
__tpl_file:             "ihs_plg_wct.rsp.j2"
__ihs_files:
  - { file_name: was.repo.9000.ihs.zip, check_sum: 13b981190168cfbdf4a57d18829dbc02fbbcf01b11f37f806a5cc4cd086a3f05 }
__plg_files:
  - { file_name: was.repo.9000.plugins.zip, check_sum: 86dcdc71f67fe74f307fc74d8919b567e618c7eec117f9a4d69c64024cca77b2 }
__wct_files:
  - { file_name: was.repo.9000.wct.zip, check_sum: 6c94685b858f1737d2cbecfb2ff9c1737db2fe119b3e64a9b7c3fbfbf21a2f7a }
__sdk_files:
  - { file_name: ibm-java-sdk-8.0-7.5-linux-x64-installmgr.zip, check_sum: 79c7110ceda50468ed7dd85915ca062249ebb837a0e56cf9693510461dbd5dfa }

__this_version:         "{{ product_version | default('9.0.0.20160526_1854') }}"
__java_version:         "{{ java_versioin | default('8.0.7005.20220209_1019') }}"

__product_id:           "\"id='com.ibm.websphere.IHS.v90'\""
__version_check:        "Installed com.ibm.websphere.IHS.v90_9.0.0.20160526_1854"
__iim_product_id:       "\"id='com.ibm.cic.agent\""
